
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/admin.csv" INTO TABLE admin CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/cares.csv" INTO TABLE cares CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/subscription.csv" INTO TABLE subscription CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/patient.csv" INTO TABLE patient CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/pro.csv" INTO TABLE pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/devices.csv" INTO TABLE devices CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/fav_recipes.csv" INTO TABLE fav_recipes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/followup.csv" INTO TABLE followup CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/objectives.csv" INTO TABLE objectives CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/report_pro.csv" INTO TABLE report_pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/diary.csv" INTO TABLE diary CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/subs_pro.csv" INTO TABLE subs_pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/sessions.csv" INTO TABLE sessions CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/session_moods.csv" INTO TABLE session_moods CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/stats.csv" INTO TABLE stats CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/global_stats.csv" INTO TABLE global_stats CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/stats_requests.csv" INTO TABLE stats_requests CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/obj_meal.csv" INTO TABLE obj_meal CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/obj_sport.csv" INTO TABLE obj_sport CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/session_recurr.csv" INTO TABLE session_recurr CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/recipes.csv" INTO TABLE recipes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/patient_likes.csv" INTO TABLE patient_likes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/PROD/pro_bill.csv" INTO TABLE pro_bill CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;