
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/admin.csv" INTO TABLE admin CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/cares.csv" INTO TABLE cares CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/subscription.csv" INTO TABLE subscription CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/patient.csv" INTO TABLE patient CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/pro.csv" INTO TABLE pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/devices.csv" INTO TABLE devices CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/fav_recipes.csv" INTO TABLE fav_recipes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/followup.csv" INTO TABLE followup CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/objectives.csv" INTO TABLE objectives CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/report_pro.csv" INTO TABLE report_pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/diary.csv" INTO TABLE diary CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/subs_pro.csv" INTO TABLE subs_pro CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/sessions.csv" INTO TABLE sessions CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/session_moods.csv" INTO TABLE session_moods CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/stats.csv" INTO TABLE stats CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/global_stats.csv" INTO TABLE global_stats CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/stats_requests.csv" INTO TABLE stats_requests CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/obj_meal.csv" INTO TABLE obj_meal CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/obj_sport.csv" INTO TABLE obj_sport CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/session_recurr.csv" INTO TABLE session_recurr CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/recipes.csv" INTO TABLE recipes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/patient_likes.csv" INTO TABLE patient_likes CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;
LOAD DATA LOCAL INFILE "C:/Users/cosmos/Desktop/mandareen/mandareen-api/CSV_Files/DEV/pro_bill.csv" INTO TABLE pro_bill CHARACTER SET utf8 COLUMNS TERMINATED BY ';' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"' LINES TERMINATED BY '
' IGNORE 1 LINES;